### ISSUE TITLE
HD video URLs now blank (API change?)

### ISSUE THREAD

**Issue by yllus** [jimporter/giantbomb-kodi#16]
I'll give making a code update a whirl myself shortly, but it looks like HD videos are no longer having their URLs returned to the Kodi add-on.

**Comment by jimporter** [comment]
Hm, it's possible. I moved recently and don't have my HTPC set up yet, so I haven't used this add-on in a while. It's possible there's an issue with API keys or something...

**Comment by yllus** [comment]
Looks like it's an API issue actually - we should sit on this and it'll likely fix itself in the next day or two: https://www.giantbomb.com/forums/bug-reporting-33/why-are-the-hd-download-links-missing-1834762/#19
