### ISSUE TITLE
Upcoming Giant Bomb API changes will break you. Please contact me

### ISSUE THREAD

**Issue by edgework** [jimporter/giantbomb-kodi#4]
RE: http://www.giantbomb.com/forums/api-developers-3017/big-changes-coming-to-api-related-to-videos-1775152

Please send me a PM  (http://www.giantbomb.com/profile/edgework/) with your email address so we can discuss this.

**Comment by jimporter** [comment]
Tracking this in #8 now.

**Comment by edgework** [comment]
Is there no way to inject a secret key?  Without that this is going to be
problematic.  The way it works is you provide a unique user agent to us and
we assign you a secret salt you will use in hashing an authentication code
for each video request. If that salt is public its pointless.  We're using
the same technology Hulu and Netflix use aren't there Kodi players for
those services?

**Comment by jimporter** [comment]
> We're using the same technology Hulu and Netflix use aren't there Kodi players for those services?

No, there aren't. Not official ones, anyway. The Hulu add-on appears to be broken, and the Netflix add-on just plays the videos inside a web browser. I think most people who want to use Hulu/Netflix on their Kodi machines just run Kodi on top of Android and then install the official apps via Android.

I can obfuscate the secret data, but that doesn't prevent people from reversing the obfuscation (the same issue applies to Hulu, Netflix, DVD CSS, etc). The hard part about cracking Netflix is that they have a bunch of crazy encryption on the video stream itself, and the only way to break that would be to reverse engineer HTML5 Encrypted Media Extensions (which I'm sure will happen sooner or later). Cracking the Netflix API, on the other hand, is easy, as I understand it.

If the videos from Giant Bomb are just MP4 files, then the most I can do is to make it *inconvenient* to get the files. Even if I could secure the add-on, all someone needs to do is run something like mitmproxy and log the responses, or alternately patch Kodi to automatically download any files it streams (you might even be able to do this now with some advanced settings).

**Comment by edgework** [comment]
OK, you can distribute the auth code in .pyc format only and write it in a
very round-about way so the pcode is extra hard to reverse engineer though.
Right?

**Comment by jimporter** [comment]
Well, sure, but then someone could just copy the .pyc file and use it in conjunction with the rest of the add-on's code to do something bad with the auth key. The part where the add-on hands off the video URL to Kodi isn't secure, and I don't know how to make it secure (or if it's even possible). Another easy way to get the MP4 file would be to just run Kodi in a debugger and set a breakpoint where the URL gets sent to Kodi.

Probably the *best* way I could secure the add-on would be to require everyone who uses it to link their Giant Bomb account. Then, at least you'd know who's doing bad things with the API and you can just ban them. Since the auth data would be per-user and generated on your server, it'd be a lot easier to keep any secrets safe.

**Comment by jimporter** [comment]
Also, I'm not 100% sure if you can make a .pyc file that's compatible with multiple versions of Python. Some systems use 2.6 and others use 2.7.

**Comment by edgework** [comment]
Ugg. I didn't realize you needed to hand off the URL to Kodi to fetch.
That's going to be a serious problem. The first being that from what I can
tell Kodi doesn't provide a user agaent. Its just "pythonLib". That's
wayyyy too generic to just whitelist. ...and once the protection goes live
its a User Agent that will be blocked at the firewall. We'd need the User
Agent for the every request to be unique to the app and the video request
is where the auth header needs to be.  Is there any other way to get Kodi
to load a video than by giving it a URL?

Once the user links their user account with http://www.giantbomb.com/kodi/
 we'd deal with tracking who's downloading what already.

**Comment by jimporter** [comment]
I can provide any User-Agent you like; it gets sent along with the URL to Kodi, like so: "http://www.example.com/file.html|User-Agent=whatever" (or something similar).

**Comment by edgework** [comment]
That's just half of it. We also need two custom headers set  x-aws-auth  ->
your auth key signing the filename ,  x-aws-key ->  users API key from the
/kodi hookup.  the signing part is what needs to be a secret as possible.

Is all that possible?

**Comment by jimporter** [comment]
It looks like I can set any HTTP header I need, although keeping it a secret is the hard part.

**Comment by edgework** [comment]
OK cool. The value in the header doesn't need to be protected, just how its
derived.

So you should have all the information you need.  Please let me know what I
need to do to bless your app.  Dominus Opus Dingus?

**Comment by edgework** [comment]
What's your GiantBomb username?

**Comment by edgework** [comment]
...duh?  After all of this I never gave you specifics. (Or if I did I
didn't record the details on our side so use this)


Every video file request needs the following headers.


*x-ews-auth*

Auth Header where you will "sign" your requests. This gives your requests
priority so they don't go though a set of firewall rules to rate
throughput, detect piracy etc.  You don't NEED it but I suggest you use it.

x-ews-auth= md5('kodi-af3d2e' + filename)    e.g.  for
v.giantbomb.com/foo/bar/quicklook.mp4  md5('kodi-af3d2e' + 'quicklook.mp4 ')

kodi-af3d2e is a unique salt assigned to you and indexed by your user agent.


*x-ews-key*

All requests for every video need to have the user's api key.

x-ews-key=abc123

**Comment by edgework** [comment]
Ugh, I didn't realize this conversation was public. Please contact me using your direct email address.
