### ISSUE TITLE
Seems like 4.2.1 is broken in kodi now?

### ISSUE THREAD

**Issue by uratrtl** [jimporter/giantbomb-kodi#5]
Love the addon,unfortunately it seems to be broken in 4.2.1 in the latest stable version available on the nexus player?

**Comment by jimporter** [comment]
Does this being closed mean that it's actually ok? I haven't tested the latest Kodi, since OpenELEC hasn't updated yet.

**Comment by uratrtl** [comment]
Yeah it was a user error, everything is running well on the latest stable version. Thanks for all the hard work too!
