### ISSUE TITLE
Outage due to API changes?

### ISSUE THREAD

**Issue by uratrtl** [jimporter/giantbomb-kodi#7]
Hi, love the addon and when I went to load one of the latest quickbooks today I'm finding it either starts the loading animation and returns me to the menu or kodi tells me, "Playback failed One or more items failed to play. Check the log for more information about this message." I was running version 4.2.1 when this started and the issue has continued when I installed v5.0a1 and relinked my account. 

Thanks for your work

Can I submit a log to you in?

**Comment by uratrtl** [comment]
http://www.giantbomb.com/forums/api-developers-3017/video-api-changes-this-is-happening-people-read-th-1786460/#3

**Comment by jimporter** [comment]
Weird, I just tried and it works fine for me.

**Comment by uratrtl** [comment]
Ok, after toggling all the settings it looks like this is happening for me when I select the HD setting after successfully linking my subscriber account. When I chose High or Low the stream loads fine. 

This is a completely satisfying workaround for me. Thanks for the speedy reply!

**Comment by jimporter** [comment]
I'll ask the Giant Bomb devs what I should do about this. HD works fine for me, but maybe it's because I haven't reset my auth lately?

**Comment by TechGremlin** [comment]
From what I can understand from what changes needed to be made, Default.py line 345, you forgot to remove the api key from the HD urls.

**Comment by jimporter** [comment]
It's less "forgot" and more "was never told I should", but I pushed a change to master either way.

**Comment by uratrtl** [comment]
Awesome! Thanks again for all the hard work!

**Comment by jimporter** [comment]
Resolved in 5.0a2.
