### ISSUE TITLE
addon not working in kodi 16

### ISSUE THREAD

**Issue by tctimmeh** [jimporter/giantbomb-kodi#9]
After upgrading to kodi 16 (Jarvis) I am no longer able to play any videos using this addon (v4.3.1). I get the following stack trace in `kodi.log`:

    ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
            Error Type: <type 'exceptions.Exception'>
            Error Contents: unknown mode: 2
            Traceback (most recent call last):
              File "/home/timmeh/.kodi/addons/plugin.video.giantbomb/default.py", line 434, in <module>
                handler.run(sys.argv[2])
              File "/home/timmeh/.kodi/addons/plugin.video.giantbomb/resources/lib/requesthandler.py", line 63, in run
                raise Exception('unknown mode: ' + mode)
              Exception: unknown mode: 2
        -->End of Python script error report<--

**Comment by jimporter** [comment]
That's really bizarre. Unfortunately, I don't have access to Kodi 16 at the moment, so I'm not sure what's going on. I'll try to get a Kodi 16 install set up and see what the deal is...

**Comment by tctimmeh** [comment]
It seems to work in a fresh install of Kodi 16. Something bad must have happened when I upgraded from 15. I've reinstalled from scratch and everything is working properly now.

**Comment by jimporter** [comment]
Cool, glad to see that everything's working for you! I'll keep an eye out for this issue when I upgrade, and if I can reproduce it, I'll try to fix it. Thanks!

**Comment by poloniculmov** [comment]
I'm getting this exception on a fresh install of Kodi 16.1 April 25 build on RetroPie, running on a Pi 3. It worked yesterday, but it stopped today. Let me know if there's any more logs I can supply you with.
